### ISSUE TITLE
When there are no modules to clean up, the script offers to remove /usr/lib/modules

### ISSUE THREAD

**Issue by RX14** [t-wissmann/archlinux-update-modules#4] opened 2019-11-23 12:00 UTC
```
$ ~/.config/zsh/archlinux-update-modules/archlinux-update-modules
> Running kernel package: name=linux version=5.3.12.arch1-1 architecture=x86_64
> The running kernel 5.3.12-arch1-1 already has a module directory /usr/lib/modules/5.3.12-arch1-1, nothing to do
> 1 old directories in /usr/lib/modules
==> Remove old module dir ?
:: sudo rm -rf /usr/lib/modules/  [y/N] n
```

This seems to have been caused by pacman beginning to emit a trailing newline, meaning mapfile starts treating it as an array of length 1.

**Comment by t-wissmann** [comment] 2019-11-29 09:50
I cannot reproduce it with pacman 5.2.1-1. And the `-t` option for mapfile actually should handle trailing newlines correctly. Do you have an example line that causes this extra newline? For example, I have tried:
```
$ printf /home/thorsten | LC_ALL=C pacman -Qoq - 2>&1 > /dev/null
error: No package owns /home/thorsten
```
So the newlines are fine. What is your output of the following commands?
```
find /usr/lib/modules -mindepth 1 -maxdepth 1 -printf "%p\n"
# and
find /usr/lib/modules -mindepth 1 -maxdepth 1 -printf "%p\n" \
   | LC_ALL=C pacman --color never -Qoq - 2>&1 > /dev/null
```
For the time being, I'm now also filtering the pacman output for lines mentioning `/usr/bin/modules`. So I guess this should circumvent your issue and might fix some future trouble for the case that pacman changes the output format.

**Comment by t-wissmann** [comment] 2019-11-29 10:13
Just to double check: Do you have bash installed on your system or did you link /bin/bash to some other shell (like sh or zsh) or did you change the shebang at the beginning of `archlinux-update-modules`? Because when I do so, I can reproduce your issues. (That said, please run the above commands in bash, not in zsh).

I'm asking because zsh seem to have different behaviour when combining `>` and `|`, which is done in the script. Take for example the commands:
```
pman() { echo 'stdout' ; echo 'std/err' >&2 ; echo 'more out' ; }
pman 2>&1 > /dev/null | sed 's,[^/]*,,'
```
On bash the output is
```
/err
```
but on zsh the output is 
```

/err

```
I guess that this is could be the source of the extra newline you are mentioning.

**Comment by RX14** [comment] 2019-11-29 13:23
Well, now I can't reproduce it either :(

Running the script with zsh produces an error, so I doubt that's what was happening. The shebang was still in place.

**Comment by t-wissmann** [comment] 2019-12-03 17:21
I have also added braces to avoid ambiguities, so I assume the issue is fixed now... If you notice any further trouble in this direction, feel free to re-open this issue.

**Closed as completed by t-wissmann** 2019-12-03 17:21 UTC
